### ISSUE TITLE
Responsive Elements

### ISSUE THREAD

**Issue by wuxishy** [tjsct/tjioi#4]
The navbar looks ugly on mobile.

**Comment by gengkev** [comment]
That's true. Generally, we ought to rely on default Bootstrap elements more, rather than writing our own CSS; that way we get all the niceties for free. But that means we'd have to rewrite stuff, which takes effort. Sigh. I guess we could try to get *just* the navbar from Bootstrap.

**Comment by wuxishy** [comment]
I think it is called `<div class="collapse navbar-collapse navbar-ex1-collapse">`?

**Comment by gengkev** [comment]
lol... unrelated, but i think you may have triggered an xss filter in the email notification, because the raw html looks like
`<p>I think it is called '</p><div>``?<p></p></div>`
but with one backtick instead of two
